# Generated by Django 5.1.7 on 2025-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
