# Generated by Django 5.1.7 on 2025-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_company_language_challenge_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='expected_output',
            field=models.TextField(default='', help_text='Exact stdout for a correct solution'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='xp_reward',
            field=models.PositiveIntegerField(default=10, help_text='XP awarded for a correct submission'),
        ),
    ]
