# Generated by Django 5.1.7 on 2025-05-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_expected_output_challenge_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.CharField(choices=[('loops', 'Loops'), ('data_structures', 'Data Structures'), ('debugging', 'Debugging')], default='loops', help_text='What topic this challenge practices.', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='challenges.company'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='challenges.language'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='xp_reward',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
