# Generated by Django 5.1.7 on 2025-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order_no',
            field=models.IntegerField(default=1),
        ),
    ]
