# Generated by Django 5.1.7 on 2025-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
