# Generated by Django 5.1.7 on 2025-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_average_rating_course_ratings_count_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
