# Generated by Django 5.1.6 on 2025-03-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
