# Generated by Django 5.1.6 on 2025-03-30 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customtoken_options_alter_customtoken_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
