# Generated by Django 5.1.7 on 2025-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userbadge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quiz_responses',
            field=models.JSONField(default=dict),
        ),
    ]
